server {
    listen 80;
    server_name localhost;

    # 1. Servíruje statické soubory (tvůj index.html)
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
    }

    # 2. Vše, co začíná na /api/, přesměruje na backend kontejner
    location /api/ {
        # Zde využíváme interní DNS Dockeru (název kontejneru a jeho port)
        # Lomítko na konci zajistí, že se /api/ ořízne, takže na backend přijde jen /weather
        proxy_pass http://weather_backend:5500/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}