version: "3.9"

services:
  db:
    image: postgres:16
    container_name: weather_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  web_be:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: weather_backend
    env_file:
      - ./.env
    environment:
      - RUNNING_IN_DOCKER=1
    depends_on:
      - db
    ports:
      - "5500:5500"

  web_fe:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: weather_frontend
    ports:
      - "8080:80"
    depends_on:
      - web_be

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml:ro
      #trvale ukládani data
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - web_be

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_DASHBOARDS_JSON_ENABLED: "true"
      GF_DASHBOARDS_JSON_PATH: /var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      #uloží se nastavení Grafany včetně Data Source
      - grafana-data:/var/lib/grafana
      #  mapování pro dashboardy
      - ./grafana:/var/lib/grafana/dashboards:ro
