global:
  scrape_interval: 15s  # jak často se sbírají metriky

scrape_configs:
  - job_name: 'weather-backend'
    metrics_path: /metrics
    static_configs:
      - targets: ['web_be:5500']  # název služby + interní port
      # http://localhost:9090/targets - diagnostika promethea

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # pro monitorování samotného Promethea