name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print working directory
        run: pwd && ls -R

      # Build frontend
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Build frontend
        run: |
          if [ -f frontend/package.json ]; then
            cd frontend
            npm install
            npm run build
          else
            echo "Frontend build skipped, žádný package.json"
          fi

      # Build backend artifact
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Build backend artifact
        run: |
          cd backend
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt, pokračuji"
          fi
          zip -r backend-artifact.zip .

      # Upload backend artifact
      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-artifact
          path: backend/backend-artifact.zip